### ISSUE TITLE
SLRE is broken (incorrect regex matching)

### ISSUE THREAD

**Issue by gemarcano** [TeamCobra/ouroboros#23]
See cesanta/slre#19 for details. Should we look for a replacement, or should we try to debug this? Their code is not straight forward, and I have little experience with regex engines. Thoughts?

**Comment by jkugs** [comment]
I managed to work around this problem by changing our regex strings slightly to:

`static const char * full_regex = "^/group/([a-z0-9-_]+)/name/([a-z0-9-_]+)$";`
`static const char * group_regex = "^/group/([a-z0-9-_]+)$";`

This will of course force urls to only contains lowercase letters, numbers, dashes, and underscores but I believe these would be sufficient. We can add to it what we wanna include. I think the problem stems from:

`[^...]  Match any character but ones from set`

Not sure why that screws it up but matching characters to a set normally seems to work correctly.

**Comment by gemarcano** [comment]
We'll use Jim's suggestion for now.
