### ISSUE TITLE
RGEN naming conflicts

### ISSUE THREAD

**Issue by gemarcano** [TeamCobra/ouroboros#30]
Certain tag names in the XML lead to metamodel class generation with names that conflict either with Ruby classes (like `<file>` -> `File`) or RGEN classes and/or methods ( `<minLength>` -> `minLength` method). Any thoughts on how we can deal with this?

**Comment by jaredsmithse** [comment]
We are just changing the name like RIT did for course numbers when they decided it would be a good idea for Oracle to make our sis system.
