### ISSUE TITLE
Refactor Makefiles 

### ISSUE THREAD

**Issue by jaredsmithse** [TeamCobra/ouroboros#34]
We need to go back through the Makefile and update it, and get rid of some of them. There seems to be Makefiles in a lot of directories that we don't necessarily need, and it makes it a pain to update them all.

**Comment by gemarcano** [comment]
I agree, although the refactoring may not reduce the number of files (in fact, they may double). I am experimenting with Autotools, and it requires a few auxiliary files. That having been said, once set up, it will allow for compilation using the normal `./configure; make; sudo make install` pattern.

**Comment by gemarcano** [comment]
Fixed with #46.
