### ISSUE TITLE
Make Testing Plan

### ISSUE THREAD

**Issue by jaredsmithse** [TeamCobra/ouroboros#47]
On 2.3.2015 we came up with a rough outline of what we will do for testing:
We should use an automated service like Jenkins to run tests when pushed to `development` branch

Using VMs from DigitalOcean or AWS, we will have two VMs:
- One for putting the generated/device code on
- One to run the tests against the other VM

Once tests have passed, merge `development` onto `master`

**Comment by gemarcano** [comment]
We talked about it, unit testing is underway.
