### ISSUE TITLE
XML variable value verificaton

### ISSUE THREAD

**Issue by ajl2612** [TeamCobra/ouroboros#69]
Currently the actual value of a field is located in the base class that all fields extend. It is defined here is as type string, but this is not the case for integers. Currently I have not found a means to redefine elements further down the inherited object tree. It may make more sense to move the value definition to base classes to avoid this issue.

**Comment by ajl2612** [comment]
Conversation with Gabe revealed that the XML is not structured the same way as the C++ code. Making the proposed change to move the value into the child classes would both fix the problem and make coding style consistent between the two.

**Comment by gemarcano** [comment]
@ajl2612, did we fix this a while back?

**Comment by gemarcano** [comment]
This was fixed a while back.
